### ISSUE TITLE
Headers API doesn't ignore case

### ISSUE THREAD

**Issue by cyco130** [lagonapp/lagon#226]
**Describe the bug**
`Headers` API should ignore letter cases but it doesn't. It causes many failures in Rakkas's integration tests.

**To Reproduce**
Run the following snippet:

```js
const headers = new Headers();
headers.append("X-Test", "1234");
console.log("HEADERS", Object.fromEntries(headers.entries()));
console.log(headers.get("X-Test")); // Prints 1234
console.log(headers.get("x-test")); // Prints undefined
```

**Expected behavior**
I expect `headers.get("x-test")` to be equal to `headers.get("X-Test")`.

**Information:**
 - OS: Linux Mint
 - Browser: Doesn't apply
 - Version: 0.3.3

**Comment by QuiiBz** [comment]
Good catch! As a note, the implementation is defined here:
- https://github.com/lagonapp/lagon/blob/eebaf9d535c9376cdccacb5a7578eae30835c9e1/packages/js-runtime/src/runtime/fetch.ts#L4
Not sure what's the best solution to fix this bug:
- Update get/append operations to find by transforming all headers to lowercase
- Always store the headers in upper/lowercase. That means the user might be surprised because we modify a header key on his behalf (it shouldn't change anything at the end, because any get operation will return the right header value no matter the case of the header key)

**Comment by cyco130** [comment]
Sounds like a perfect first PR opportunity :)

I haven't looked at the spec but Chrome, Firefox, Deno, and Node (with `--experimental-fetch`) all return `"x-test"` for `[...new Headers({ "X-Test" : "1234" })][0][0]`. The end user has very few ways to observe the behavior so I think storing everything in lowercase should be OK.

Would you accept a [`getSetCookie` or `getAll("set-cookie")`](https://github.com/whatwg/fetch/pull/1346) implementation in the same PR or should we open a discussion issue for that?

**Comment by cyco130** [comment]
The spec also seems to [approve of storing in lowercase](https://fetch.spec.whatwg.org/#convert-header-names-to-a-sorted-lowercase-set).

**Comment by QuiiBz** [comment]
> The spec also seems to [approve of storing in lowercase](https://fetch.spec.whatwg.org/#convert-header-names-to-a-sorted-lowercase-set).

Sounds great. Let's go this way, and let me know if you want to submit a PR for this :)

> Would you accept a https://github.com/whatwg/fetch/pull/1346 implementation in the same PR or should we open a discussion issue for that?

I would prefer opening a new issue, since it's not directly related to this bug.
