### ISSUE TITLE
Build step needed

### ISSUE THREAD

**Issue by ming535** [lagonapp/lagon#590]
**Describe the bug**
cargo build failed.
**Screenshots**
```bash
error: couldn't read crates/runtime_isolate/src/../runtime.js: No such file or directory (os error 2)
 --> crates/runtime_isolate/src/options.rs:6:26
  |
6 | const JS_RUNTIME: &str = include_str!("../runtime.js");
```
It seems that the js file needed to be generated first, any documentation on how to build the project?

**Comment by QuiiBz** [comment]
You should be able to run the `build` script at the root of the monorepo, which first builds `packages/js-runtime` and then builds the Rust crates that depend on it.

You can also manually run the `build` script inside `packages/js-runtime` instead of relying on Turborepo.

We have a [contributing documentation](https://docs.lagon.app/contributing) but it's not yet complete. Should be done in the next few days.
